# circleCI build file
version: 2.1
jobs:
  build:
    docker:
      - image: yakworks/builder:jdk11
    # resource_class: 'large'

    steps:
      - checkout

      - run: make cache-key-file
      - restore_cache: &gradle-cache-restore
          key: gradle-{{ checksum "cache-key.tmp" }}

      - run: make gradle.resolve-dependencies

      - save_cache:
          paths: [ "~/.m2", "~/.gradle" ]
          key: gradle-{{ checksum "cache-key.tmp" }}

      - run: make compile

      - run:
          name: ✔︎ -- Test
          command: make check

      # merge test results to store in circle
      - run:
          name: ✔︎ -- Merge Test Results
          when: always
          command: make merge-test-results

      - store_test_results:
          path: build/test-results/
      - store_artifacts:
          path: build/reports/
          destination: /
      - save_cache:
          paths: [ ".gradle", "./build", "./grails-kit/build", "./grails-jasper/build"]
          key: build-{{ .Branch }}-{{ .Revision }}

  ship-it:
    docker:
      - image: yakworks/builder:jdk11
    # resource_class: 'medium+'

    steps:
      - checkout
      - run: make cache-key-file
      - restore_cache: *gradle-cache-restore
      - restore_cache:
          key: build-{{ .Branch }}-{{ .Revision }}

      # download vault and decrypts
      - run: make vault.decrypt
      # sets up git config, kubectl and docker login
      - run: make ship.authorize
      # publish libs, push docker, kubernetes deploy
      - run: make ship.release
      # add to changelog, creates a release to github, rolls version.props and pushes changes to github
      # only happens if IS_RELEASABLE, meaning if its a snapshot then it skips this
      - run: make ship.version

workflows:
  build-flow:
    jobs:
      - build:
          context: bot-context #context with shared ENV vars
      - ship-it:
          context: bot-context
          requires: [build]
          filters: { branches: { only: [ master, /release\/.*/, dev ] } }
