logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate.orm.deprecation: OFF # turns off deprecation notices
    # uncomment to turn on sql logging
#    org.hibernate.stat: DEBUG
#    org.hibernate.SQL: DEBUG

hibernate:
  format_sql: false
  naming_strategy: 'org.hibernate.cfg.DefaultNamingStrategy'
  show_sql: false
  cache:
    queries: false
    use_second_level_cache: false
    use_query_cache: false
  jdbc:
    time_zone: 'UTC'
  enhancer:
    enableLazyInitialization: true
    enableAssociationManagement: true

dataSource:
  pooled: true
  jmxExport: true
  driverClassName: org.h2.Driver
  username: sa
  password:
  dbCreate: create-drop
  url: jdbc:h2:mem:testDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
